db.user.insert({'name':'gavin', 'email':'admin@vwarn.com'});
db.config.insert({'key':'timeline.headline', 'value':'九三散人的生活轨迹'});
db.config.insert({'key':'timeline.text', 'value':'记录九三散人的生活与工作中的点点滴滴'});
db.config.insert({'key':'timeline.startdate', 'value':'2017,1,1'});
db.config.insert({'key':'info.introduce', 'value':'&nbsp;&nbsp;这是一个奋斗中的程序员的个人主页，主要介绍自己在日常工作学习中记录遇到的各种问题以及编程技术讨论的地方。九三散人：软件界的小学生，主要做Java类技术开发，热衷于软件技术研究。'});
db.config.insert({'key':'config.baidu.url', 'value':'http://data.zz.baidu.com/urls?site=www.0x12345.com&token=j4LHAhXmOzbwVjSB'})
db.config.insert({'key':'email.smtp.server', 'value':'smtp.ym.163.com'});
db.config.insert({'key':'email.username', 'value':'public@0x12345.com'});
db.config.insert({'key':'email.password', 'value':'....'});
db.config.insert({'key':'post.comment.flag', 'value':'0'});